{
 "title": "Mikrotik",
 "description": "Mikrotik RouterOS metrics",
 "tags": [
  "dashboard",
  "mikrotik"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": "label_values(mikrotik_system_uptime,address)"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System version and hw",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mikrotik_system_uptime{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "{{version}} on {{boardname}}",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mikrotik_system_uptime{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP leases Private",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mikrotik_dhcp_leases_active_count{address=\"$node\",server=\"private\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "DHCP leases" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP leases Public",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mikrotik_dhcp_leases_active_count{address=\"$node\",server=\"public\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "DHCP leases" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mikrotik_system_cpu_load{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mikrotik_system_total_memory{address=\"$node\"} - mikrotik_system_free_memory{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mikrotik_system_cpu_load{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mikrotik_system_total_hdd_space{address=\"$node\"} - mikrotik_system_free_hdd_space{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mikrotik_system_total_hdd_space{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mikrotik_interface_rx_byte{address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mikrotik_interface_tx_byte{address=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out - {{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "mikrotik_dhcp_leases_metrics{address=\"$node\"}"
    }
   ]
  },
  { "title": "Interface status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mikrotik_interface_rx_error{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "InErrors {{interface}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mikrotik_interface_tx_error{address=\"$node\"}",
     "legendFormat": "Out Errors {{interface}}"
    }
   ]
  },
  {
   "title": "Interface status (operational)",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "mikrotik_monitor_status{address=\"$node\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Interface  rate",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "targets": [
    {
     "expr": "mikrotik_monitor_rate{address=\"$node\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Port Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mikrotik_monitor_rate{address=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}