{
 "title": "Transmission",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "torrent",
    "label": "torrent",
    "query": "label_values(transmission_torrent_added, name)"
   }
  ]
 },
 "panels": [
  { "title": "Downloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downloads (bytes/second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(transmission_torrent_download_bytes{name=~\"$torrent\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Uploads (bytes/second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(transmission_torrent_upload_bytes{name=~\"$torrent\"}) by (name) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Torrents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(transmission_torrent_done{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_ratio{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_leechers{name=~\"$torrent\"}) by (name)"
    },
    {
     "expr": "max(transmission_torrent_seeders{name=~\"$torrent\"}) by (name)"
    }
   ]
  }
 ]
}